### ISSUE TITLE
Errors in building pcl-core.wasm

### ISSUE THREAD

**Issue by lengoanhcat** [luoxuhai/pcl.js#14]
# Steps taken:
* Run devcontainer.json on Visual Studio Code 
* Run a build script `source ./scripts/build.sh`
  Below are errors:
```node ➜ /workspaces/pcl.js (feat/segmentation ✗) $ bash ./scripts/build.sh 
/workspaces/pcl.js
./scripts/build.sh: line 15: [: ==: unary operator expected
configure: cmake -DCMAKE_BUILD_TYPE=Debug -DPCL_ROOT=/workspace/pcl.js/core/pcl .. -DCMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-threads
-- /workspaces/pcl.js/src/bind/common.cpp
-- /workspaces/pcl.js/src/bind/embind.cpp
-- /workspaces/pcl.js/src/bind/filters.cpp
-- /workspaces/pcl.js/src/bind/io.cpp
-- /workspaces/pcl.js/src/bind/kdtree.cpp
-- /workspaces/pcl.js/src/bind/keypoints.cpp
-- /workspaces/pcl.js/src/bind/octree.cpp
-- /workspaces/pcl.js/src/bind/point_types.cpp
-- /workspaces/pcl.js/src/bind/registration.cpp
-- Configuring done
-- Generating done
-- Build files have been written to: /workspaces/pcl.js/src/bind/build
make: make -j
[ 10%] Building CXX object CMakeFiles/pcl-core.dir/common.cpp.o
[ 30%] Building CXX object CMakeFiles/pcl-core.dir/io.cpp.o
[ 30%] Building CXX object CMakeFiles/pcl-core.dir/embind.cpp.o
[ 40%] Building CXX object CMakeFiles/pcl-core.dir/filters.cpp.o
[ 60%] Building CXX object CMakeFiles/pcl-core.dir/keypoints.cpp.o
[ 60%] Building CXX object CMakeFiles/pcl-core.dir/kdtree.cpp.o
[ 70%] Building CXX object CMakeFiles/pcl-core.dir/octree.cpp.o
[ 80%] Building CXX object CMakeFiles/pcl-core.dir/point_types.cpp.o
[ 90%] Building CXX object CMakeFiles/pcl-core.dir/registration.cpp.o
/workspaces/pcl.js/src/bind/common.cpp:1:10: fatal error: 'pcl/io/pcd_io.h' file not found
#include <pcl/io/pcd_io.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
em++: error: '/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=17 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -I/workspace/pcl.js/core/pcl/build/include/pcl-1.12 -I/workspace/pcl.js/core/pcl/wasm/deps/boost/build/include -I/workspace/pcl.js/core/pcl/wasm/deps/eigen -I/workspace/pcl.js/core/pcl/wasm/deps/flann/build/include -g3 -std=gnu++14 -MD -MT CMakeFiles/pcl-core.dir/common.cpp.o -MF CMakeFiles/pcl-core.dir/common.cpp.o.d -c /workspaces/pcl.js/src/bind/common.cpp -o CMakeFiles/pcl-core.dir/common.cpp.o' failed (returned 1)
make[2]: *** [CMakeFiles/pcl-core.dir/build.make:77: CMakeFiles/pcl-core.dir/common.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/workspaces/pcl.js/src/bind/registration.cpp:2:10: fatal error: 'pcl/point_types.h' file not found
#include <pcl/point_types.h>
         ^~~~~~~~~~~~~~~~~~~
/workspaces/pcl.js/src/bind/filters.cpp:2:10: fatal error: 'pcl/point_types.h' file not found
#include <pcl/point_types.h>
         ^~~~~~~~~~~~~~~~~~~
/workspaces/pcl.js/src/bind/point_types.cpp:2:10: fatal error: 'pcl/point_types.h' file not found
#include <pcl/point_types.h>
         ^~~~~~~~~~~~~~~~~~~
/workspaces/pcl.js/src/bind/io.cpp:2:10: fatal error: 'pcl/io/pcd_io.h' file not found
#include <pcl/io/pcd_io.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
em++: error: '/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=17 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -I/workspace/pcl.js/core/pcl/build/include/pcl-1.12 -I/workspace/pcl.js/core/pcl/wasm/deps/boost/build/include -I/workspace/pcl.js/core/pcl/wasm/deps/eigen -I/workspace/pcl.js/core/pcl/wasm/deps/flann/build/include -g3 -std=gnu++14 -MD -MT CMakeFiles/pcl-core.dir/registration.cpp.o -MF CMakeFiles/pcl-core.dir/registration.cpp.o.d -c /workspaces/pcl.js/src/bind/registration.cpp -o CMakeFiles/pcl-core.dir/registration.cpp.o' failed (returned 1)
1 error generated.
1 error generated.
1 error generated.
em++: error: '/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=17 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -I/workspace/pcl.js/core/pcl/build/include/pcl-1.12 -I/workspace/pcl.js/core/pcl/wasm/deps/boost/build/include -I/workspace/pcl.js/core/pcl/wasm/deps/eigen -I/workspace/pcl.js/core/pcl/wasm/deps/flann/build/include -g3 -std=gnu++14 -MD -MT CMakeFiles/pcl-core.dir/filters.cpp.o -MF CMakeFiles/pcl-core.dir/filters.cpp.o.d -c /workspaces/pcl.js/src/bind/filters.cpp -o CMakeFiles/pcl-core.dir/filters.cpp.o' failed (returned 1)
em++: error: '/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=17 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -I/workspace/pcl.js/core/pcl/build/include/pcl-1.12 -I/workspace/pcl.js/core/pcl/wasm/deps/boost/build/include -I/workspace/pcl.js/core/pcl/wasm/deps/eigen -I/workspace/pcl.js/core/pcl/wasm/deps/flann/build/include -g3 -std=gnu++14 -MD -MT CMakeFiles/pcl-core.dir/point_types.cpp.o -MF CMakeFiles/pcl-core.dir/point_types.cpp.o.d -c /workspaces/pcl.js/src/bind/point_types.cpp -o CMakeFiles/pcl-core.dir/point_types.cpp.o' failed (returned 1)
make[2]: *** [CMakeFiles/pcl-core.dir/build.make:197: CMakeFiles/pcl-core.dir/registration.cpp.o] Error 1
em++: error: '/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=17 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -I/workspace/pcl.js/core/pcl/build/include/pcl-1.12 -I/workspace/pcl.js/core/pcl/wasm/deps/boost/build/include -I/workspace/pcl.js/core/pcl/wasm/deps/eigen -I/workspace/pcl.js/core/pcl/wasm/deps/flann/build/include -g3 -std=gnu++14 -MD -MT CMakeFiles/pcl-core.dir/io.cpp.o -MF CMakeFiles/pcl-core.dir/io.cpp.o.d -c /workspaces/pcl.js/src/bind/io.cpp -o CMakeFiles/pcl-core.dir/io.cpp.o' failed (returned 1)
make[2]: *** [CMakeFiles/pcl-core.dir/build.make:107: CMakeFiles/pcl-core.dir/filters.cpp.o] Error 1
make[2]: *** [CMakeFiles/pcl-core.dir/build.make:122: CMakeFiles/pcl-core.dir/io.cpp.o] Error 1
make[2]: *** [CMakeFiles/pcl-core.dir/build.make:182: CMakeFiles/pcl-core.dir/point_types.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/pcl-core.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
emmake: error: 'make -j' failed (returned 2)
cp: cannot stat 'pcl-core.wasm': No such file or directory
```
# Expectation:

Build pcl-core.wasm successfully

# Potential solutions:

set -DINCLUDE_DIRECTORIES

**Comment by luoxuhai** [comment]
Looks like PCL is not compiled. 
Please try:
```bash
source ./scripts/build-pcl.sh
source ./scripts/build.sh
```

**Comment by lengoanhcat** [comment]
@luoxuhai : I successfully compiled pcl and pcl-core.wasm in my local env though I have to modify codes of pcl and flann libraries a bit. I shall submit a PR after running a few tests in `pcl.js/test` folder.

As I cannot find any relevant document about how to run test, I am doing the following steps to run `pcl.js/tests/common.ts`

```bash
cd /workspaces/pcl.js/tests/
tsc common.ts 
nodejs common.js
```

I have the following errors

```
internal/modules/cjs/loader.js:329
      throw err;
      ^

Error: Cannot find module '/workspaces/pcl.js/dist/pcl.cjs.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/workspaces/pcl.js/tests/common.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/workspaces/pcl.js/package.json',
  requestPath: '../'
  ```

Disclaimer: I am a newbie to Nodejs; hence, it might be just my lack of experience.

**Comment by luoxuhai** [comment]
@lengoanhcat 

The following steps will run all tests:

```bash
cd /workspaces/pcl.js
npm install
npm run test
```

**Comment by luoxuhai** [comment]
> @luoxuhai : I successfully compiled pcl and pcl-core.wasm in my local env though I have to modify codes of pcl and flann libraries a bit. I shall submit a PR after running a few tests in `pcl.js/tests` folder.
> 
> As I cannot find any relevant document about how to run test, I am doing the following steps to run `pcl.js/tests/common.ts`
> 
> ```shell
> cd /workspaces/pcl.js/tests/
> tsc common.ts 
> nodejs common.js
> ```
> 
> I have the following errors
> 
> ```
> internal/modules/cjs/loader.js:329
>       throw err;
>       ^
> 
> Error: Cannot find module '/workspaces/pcl.js/dist/pcl.cjs.js'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (internal/modules/cjs/loader.js:321:19)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
>     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
>     at Module.require (internal/modules/cjs/loader.js:974:19)
>     at require (internal/modules/cjs/helpers.js:93:18)
>     at Object.<anonymous> (/workspaces/pcl.js/tests/common.js:6:11)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32) {
>   code: 'MODULE_NOT_FOUND',
>   path: '/workspaces/pcl.js/package.json',
>   requestPath: '../'
> ```
> 
> Disclaimer: I am a newbie to Nodejs; hence, it might be just my lack of experience.

I added [Contributing Guide](https://github.com/luoxuhai/pcl.js/blob/master/CONTRIBUTING.md) and it fixed the bug of failing to build PCL

**Comment by lengoanhcat** [comment]
@luoxuhai is it normal to have 20MB pcl-core.wasm ? I guess not as you mentioned its size ~ 200KB on the main README.m. Atm, I am running the test suites without any success.

```node ➜ /workspaces/pcl.js (master ✗) $ npm run test

> pcl.js@1.1.0 test /workspaces/pcl.js
> jest



Test Suites: 0 of 11 total

Test Suites: 0 of 11 total
Tests:       0 total
Snapshots:   0 total
Time:        32 s
```

**Comment by luoxuhai** [comment]
@lengoanhcat pcl-core.wasm(20MB) may be a debug version.

1. Run `npm run build` to create these files in the `/dist` directory:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/37284154/189484386-b3f48953-25c6-4d43-9a41-b9db3f7f3397.png">

2. Run `npm run test`

**Comment by lengoanhcat** [comment]
I am trying to make a PR to make building in devcontainer work smoother; however, i don't have an authorisation to submit a PR ( I think ).

Here is the diff:

```
diff --git a/package.json b/package.json
index adc4afc..4e250cf 100644
--- a/package.json
+++ b/package.json
@@ -10,8 +10,8 @@
     "dev:wasm": "sh scripts/build.sh",
     "dev": "npm run dev:wasm && npm run dev:js",
     "build:js": "rollup -c",
-    "build:wasm": "sh scripts/build.sh Release",
-    "build:pcl": "sh scripts/build-pcl.sh",
+    "build:wasm": "bash scripts/build.sh Release",
+    "build:pcl": "bash scripts/build-pcl.sh",
     "build": "npm run build:wasm && npm run build:js",
     "prebuild": "npm run clean",
     "postbuild": "rimraf dist/types/.temp",
diff --git a/scripts/build-pcl.sh b/scripts/build-pcl.sh
old mode 100644
new mode 100755
index d751ddc..7cb934f
--- a/scripts/build-pcl.sh
+++ b/scripts/build-pcl.sh
@@ -1,6 +1,6 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-PCL_DIR=$(dirname $0)/core/pcl
-
-cd PCL_DIR
-sh build-wasm.sh
+PCL_DIR=$(pwd)/core/pcl
+echo $PCL_DIR
+cd $PCL_DIR
+bash build-wasm.sh
\ No newline at end of file
diff --git a/scripts/build.sh b/scripts/build.sh
old mode 100644
new mode 100755
index 5e45557..2292a30
--- a/scripts/build.sh
+++ b/scripts/build.sh
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 PROJECT_ROOT=$(pwd)
 WASM_OUT_DIR=${PROJECT_ROOT}/dist
@@ -12,7 +12,7 @@ echo $(pwd)
 mkdir -p ${EMBIND_BUILD_DIR}
 cd ${EMBIND_BUILD_DIR}
 
-if [ $1 == Release ]; then
+if [ $1 = "Release" ]; then
   BUILD_TYPE=Release
 else
   BUILD_TYPE=Debug
```

Very nice introduction [Command introduction](https://github.com/luoxuhai/pcl.js/blob/master/CONTRIBUTING.md#command-introduction) :pray:
